services:
  redis:
    # Use the 'redis-stack' image instead of standard 'redis'. This image comes pre-configured with RedisJSON, RediSearch, and other modules (plus Redis Insight) already active. 
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis Server
      - "6300:8001"  # Redis Insight
    restart: unless-stopped